services:

  postgres:
    image: postgres:16
    container_name: rentout_postgres
    restart: always
    env_file:
      - .env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: rentout_redis
    restart: always

  django:
    image: favascv/rentoutin-backend:latest
    container_name: rentout_django
    restart: always
    env_file:
      - .env.production
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - postgres
      - redis
    expose:
      - "8000"

  celery:
    image: favascv/rentoutin-celery:latest
    container_name: rentout_celery
    command: sh -c "celery -A config worker -B -l info"
    restart: always
    env_file:
      - .env.production
    depends_on:
      - postgres
      - redis

  fastapi:
    image: favascv/rentoutin-fastapi:latest
    container_name: rentout_fastapi
    restart: always
    env_file:
      - .env.production
    volumes:
      - chroma_data:/app/chroma_db
    expose:
      - "8001"

  nginx:
    image: favascv/rentoutin-nginx:latest
    container_name: rentout_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - django
      - fastapi

volumes:
  postgres_data:
  static_volume:
  media_volume:
  chroma_data: